[2023-04-29 20:18:48,228] ERROR log_exception() L1449 Exception on /pets/1 [PUT] - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Meu Drive\puc\sprint1\back_end\app.py", line 89, in update_pet
    logger.debug(f"Alterando o pet: '{pet.nome}'")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Logger.log() missing 1 required positional argument: 'msg'
[2023-04-29 20:18:48,373] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:18:48] "[35m[1mPUT /pets/1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:18:56,127] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:18:56] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:19:06,779] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:19:06] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:43:08,981] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:43:08] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:43:08,982] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:43:08] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:43:08,984] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:43:08] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:43:09,157] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:43:09] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:50:31,631] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.103:5000 (Press CTRL+C to quit) - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:54:21,133] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:54:21] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:54:23,523] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:54:23] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:54:30,808] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:54:30] "OPTIONS /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:54:31,069] ERROR log_exception() L1449 Exception on /pets/1 [PUT] - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: update_pet() missing 1 required positional argument: 'request'
[2023-04-29 20:54:31,080] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:54:31] "[35m[1mPUT /pets/1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:00,328] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.103:5000 (Press CTRL+C to quit) - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:10,615] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:10] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:10,740] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:10] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:10,744] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:10] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:10,747] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:10] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:10,802] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:10] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:10,805] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:10] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:46,065] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:46] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:05:51,278] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:05:51] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:06:00,362] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:06:00] "OPTIONS /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:06:00,693] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:06:00] "PUT /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:06:00,710] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:06:00] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 21:06:08,477] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 21:06:08] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
